name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - main
      - staging

env:
  IMAGE_NAME: my-application
  REGISTRY: ghcr.io/my-org

jobs:
  install-test-scan:
    if: startsWith(github.ref_name, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: echo "installing dependencies"

      - name: Run unit tests
        run: echo "running unit test"

      - name: Scan for vulnerabilities
        run: echo "scanning for security vulnerabilities"
        

  build-and-push-image:
    if: github.ref_name == 'main' || github.ref_name == 'staging'
    needs: [require-approval]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(git describe --tags --abbrev=0 --always)
          if [ "${{ github.ref_name }}" == "staging" ]; then
            IMAGE_TAG="${IMAGE_TAG}-stg"
          fi
          echo build docker images

      - name: Push Docker image
        run: |
          echo push docker image to container registry


  require-approval:
    if: github.ref_name == 'main' || github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://github.com/${{ github.repository }}/pulls
    steps:
      - name: Request approval
        run: echo "Approval required to merge into ${{ github.ref_name }}"
